# El Jezi Ghassen — broker MQTT local (développement)
listener 1883
allow_anonymous true
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# WebSocket optionnel (clients web / tests)
listener 9001
protocol websockets
